kind: pipeline
type: docker
name: default

steps:
  - name: Build
    image: node:20
    commands:
      - npm install
      - npm run build

  - name: Upload
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: address
      username: root
      password:
        from_secret: ssh_password
      source: 
        - .next/standalone
        - .next/static
        - public
      # Pointing to the specific volume's data directory
      target: /var/lib/docker/volumes/website/_data
      strip_components: 0

  - name: Deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: address
      username: root
      password:
        from_secret: ssh_password
      script:
        - docker stop website || true
        - docker rm website || true
        - |
          docker run -d \
            --name website \
            --restart always \
            -p 880:3000 \
            -p 7443:3000 \
            -v website:/app \
            -w /app/.next/standalone \
            node:20-alpine node server.js
