kind: pipeline
type: docker
name: default

steps:
  - name: Build
    image: node:20
    commands:
      - npm install
      - npm run build
      # Next.js standalone needs these folders to be copied manually to the standalone folder
      - cp -rv public .next/standalone/
      - mkdir -p .next/standalone/.next/static
      - cp -rv .next/static/* .next/standalone/.next/static/

  - name: Upload
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: address
      username: root
      password:
        from_secret: ssh_password
      # We only need to upload the prepared standalone folder now
      source: .next/standalone
      target: /var/lib/docker/volumes/website/_data
      strip_components: 2 # This removes ".next/standalone" from the path so files go directly into _data

  - name: Deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: address
      username: root
      password:
        from_secret: ssh_password
      script:
        - docker stop website || true
        - docker rm website || true
        - |
          docker run -d \
            --name website \
            --restart always \
            -p 880:3000 \
            -p 7443:3000 \
            -v website:/app \
            -w /app \
            node:20-alpine node server.js
